### ISSUE TITLE
[Bugs]Build OK but run error in ArchLinux

### ISSUE THREAD

**Issue by zxp19821005** [akuse-app/Akuse#11]
**Describe the bug**
I'm trying to port it to ArchLinux AUR,here is the `PKGBUILD` file:
**PKGBUILD**
```
# Maintainer: zxp19821005 <zxp19821005 at 163 dot com>
pkgname=akuse
_pkgname=Akuse
pkgver=0.1.0
pkgrel=1
pkgdesc="Simple and easy to use anime streaming desktop app without ads."
arch=('any')
url="https://github.com/akuse-app/Akuse"
license=('GPL3')
conflicts=("${pkgname}")
depends=('bash' 'electron25')
makedepends=('gendesk' 'npm' 'nodejs')
source=("${pkgname}-${pkgver}.zip::${url}/archive/refs/tags/${pkgver}.zip"
    "${pkgname}.sh")
sha256sums=('e8ab3647d89ebbc277ab9833aa7723139a7722184c067f13a91e830551e23f06'
            'b24142f7a1722021cf93134af3eccc3ced1b484500f7ee7d8f22a54b594329aa')
build() {
    gendesk -q -f -n --categories "AudioVideo" --name "${_pkgname}" --exec "${pkgname}"
    cd "${srcdir}/${_pkgname}-${pkgver}"
    sed -e '81,83d' -e '/"deb"/d' -e 's|"AppImage",|"AppImage"|g' -i package.json
    npm install
    npm run dist:linux
}
package() {
    install -Dm755 "${srcdir}/${pkgname}.sh" "${pkgdir}/usr/bin/${pkgname}"
    install -Dm644 "${srcdir}/${_pkgname}-${pkgver}/dist/linux-unpacked/resources/app.asar" -t "${pkgdir}/opt/${pkgname}/resources"
    install -Dm644 "${srcdir}/${pkgname}.desktop" -t "${pkgdir}/usr/share/applications"
    install -Dm644 "${srcdir}/${_pkgname}-${pkgver}/assets/img/icon/icon.png" "${pkgdir}/usr/share/pixmaps/${pkgname}.png"
    install -Dm644 "${srcdir}/${_pkgname}-${pkgver}/LICENSE" -t "${pkgdir}/usr/share/licenses/${pkgname}"
}
```
**akuse.sh**
```
#!/bin/bash
_ELECTRON=/usr/bin/electron25
APPDIR="/opt/akuse"
export PATH="${APPDIR}:${APPDIR}/usr/sbin:${PATH}"
export XDG_DATA_DIRS="./share/:/usr/share/gnome:/usr/local/share/:/usr/share/:${XDG_DATA_DIRS}"
export LD_LIBRARY_PATH="${APPDIR}/usr/lib:${LD_LIBRARY_PATH}"
export XDG_DATA_DIRS="${APPDIR}"/usr/share/:"${XDG_DATA_DIRS}":/usr/share/gnome/:/usr/local/share/:/usr/share/
export GSETTINGS_SCHEMA_DIR="${APPDIR}/usr/share/glib-2.0/schemas:${GSETTINGS_SCHEMA_DIR}"
_ASAR="${APPDIR}/resources/app.asar"
if [[ $EUID -ne 0 ]] || [[ $ELECTRON_RUN_AS_NODE ]]; then
    exec ${_ELECTRON} ${_ASAR} "$@"
else
    exec ${_ELECTRON} ${_ASAR} --no-sandbox "$@"
fi
```
It run well when I make it,but an error occured when I run it:
```
$ electron25 src/Akuse-0.1.0/dist/linux-unpacked/resources/app.asar 
App threw an error during load
Error: Cannot find module './modules/clientData.js'
Require stack:
- /home/zxp-endeavouros/.cache/paru/clone/akuse/src/Akuse-0.1.0/dist/linux-unpacked/resources/app.asar/src/main.js
- /usr/lib/electron25/resources/default_app.asar/main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:1082:15)
    at n._resolveFilename (node:electron/js2c/browser_init:2:117760)
    at Module._load (node:internal/modules/cjs/loader:927:27)
    at f._load (node:electron/js2c/asar_bundle:2:13377)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/home/zxp-endeavouros/.cache/paru/clone/akuse/src/Akuse-0.1.0/dist/linux-unpacked/resources/app.asar/src/main.js:8:20)
    at Module._compile (node:internal/modules/cjs/loader:1269:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1324:10)
    at Module.load (node:internal/modules/cjs/loader:1124:32)
```
```
$ ./src/Akuse-0.1.0/dist/linux-unpacked/akuse-beta 
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module './modules/clientData.js'
Require stack:
- /home/zxp-endeavouros/.cache/paru/clone/akuse/src/Akuse-0.1.0/dist/linux-unpacked/resources/app.asar/src/main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:1082:15)
    at n._resolveFilename (node:electron/js2c/browser_init:2:117684)
    at Module._load (node:internal/modules/cjs/loader:927:27)
    at f._load (node:electron/js2c/asar_bundle:2:13377)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/home/zxp-endeavouros/.cache/paru/clone/akuse/src/Akuse-0.1.0/dist/linux-unpacked/resources/app.asar/src/main.js:8:20)
    at Module._compile (node:internal/modules/cjs/loader:1269:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1324:10)
    at Module.load (node:internal/modules/cjs/loader:1124:32)
```
```
$ ./src/Akuse-0.1.0/dist/Akuse-0.1.0.AppImage 
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module './modules/clientData.js'
Require stack:
- /tmp/.mount_Akuse-Zrqw0E/resources/app.asar/src/main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:1082:15)
    at n._resolveFilename (node:electron/js2c/browser_init:2:117684)
    at Module._load (node:internal/modules/cjs/loader:927:27)
    at f._load (node:electron/js2c/asar_bundle:2:13377)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/tmp/.mount_Akuse-Zrqw0E/resources/app.asar/src/main.js:8:20)
    at Module._compile (node:internal/modules/cjs/loader:1269:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1324:10)
    at Module.load (node:internal/modules/cjs/loader:1124:32)
```

**Operative System:**
OS : EndeavourOS x86_64 6.1.58-1-lts
DE : Cinnamon
nodejs : 18.17.1
npm : 9.6.7

**Comment by aleganza** [comment]
it saya clientData.js file is missing, if you look at the README it explains how to configure one.

**Comment by zxp19821005** [comment]
Thanks.It's my fault.I've ported it to ArchLinux AUR : https://aur.archlinux.org/packages/akuse
